<?php

namespace ContainerJgyw0gc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A83fPFuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A83fPFu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A83fPFu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\UsuarioController::autenticarSesion' => ['privates', '.service_locator.k7.HWhG', 'get_ServiceLocator_K7_HWhGService', true],
            'App\\Controller\\UsuarioController::errorSesion' => ['privates', '.service_locator.k7.HWhG', 'get_ServiceLocator_K7_HWhGService', true],
            'App\\Controller\\UsuarioController::panelAdministrador' => ['privates', '.service_locator.eHmc8om', 'get_ServiceLocator_EHmc8omService', true],
            'App\\Controller\\UsuarioController::panelCliente' => ['privates', '.service_locator.eHmc8om', 'get_ServiceLocator_EHmc8omService', true],
            'App\\Controller\\UsuarioController::save' => ['privates', '.service_locator.akxvtl7', 'get_ServiceLocator_Akxvtl7Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\UsuarioController:autenticarSesion' => ['privates', '.service_locator.k7.HWhG', 'get_ServiceLocator_K7_HWhGService', true],
            'App\\Controller\\UsuarioController:errorSesion' => ['privates', '.service_locator.k7.HWhG', 'get_ServiceLocator_K7_HWhGService', true],
            'App\\Controller\\UsuarioController:panelAdministrador' => ['privates', '.service_locator.eHmc8om', 'get_ServiceLocator_EHmc8omService', true],
            'App\\Controller\\UsuarioController:panelCliente' => ['privates', '.service_locator.eHmc8om', 'get_ServiceLocator_EHmc8omService', true],
            'App\\Controller\\UsuarioController:save' => ['privates', '.service_locator.akxvtl7', 'get_ServiceLocator_Akxvtl7Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\UsuarioController::autenticarSesion' => '?',
            'App\\Controller\\UsuarioController::errorSesion' => '?',
            'App\\Controller\\UsuarioController::panelAdministrador' => '?',
            'App\\Controller\\UsuarioController::panelCliente' => '?',
            'App\\Controller\\UsuarioController::save' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\UsuarioController:autenticarSesion' => '?',
            'App\\Controller\\UsuarioController:errorSesion' => '?',
            'App\\Controller\\UsuarioController:panelAdministrador' => '?',
            'App\\Controller\\UsuarioController:panelCliente' => '?',
            'App\\Controller\\UsuarioController:save' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
